// Companion AI Policy Tracker — dataset
// Berkman Klein Center, Harvard University. Last verified: 13 August 2026.
// Contributions welcome — see CONTRIBUTING.md.

const MECHS = [
  ["disclosure",       "Non-human disclosure", "Non-human disclosure"],
  ["crisis",           "Crisis / self-harm protocol", "Crisis protocol"],
  ["reporting",        "Transparency reporting", "Transparency reporting"],
  ["minorContent",     "Sexual / harmful content limits (minors)", "Content limits (minors)"],
  ["ageAssurance",     "Age assurance or verification", "Age assurance"],
  ["parental",         "Parental consent or controls", "Parental consent"],
  ["engagement",       "Engagement / addictive design limits", "Engagement limits"],
  ["dependence",       "Bars simulating dependence or distress", "Bars dependence sim"],
  ["memory",           "Memory or retention constraint", "Memory constraint"],
  ["proImpersonation", "Bars impersonating licensed professionals", "Bars pro impersonation"],
  ["sentience",        "Bars claims of humanness or sentience", "Bars sentience claims"],
  ["audit",            "Independent audit", "Independent audit"],
  ["training",         "Limits training on user / minor data", "Training data limits"],
  ["accessBan",        "Outright minor access ban", "Minor access ban"],
  ["humanTakeover",    "Human takeover on crisis", "Human takeover"],
  ["causation",        "Duty to test own design against harm", "Duty to test design"]
];

const DATA = [
/* ============================ US FEDERAL ============================ */
{
  id:"us-guard", juris:"US Federal", body:"US Congress", cite:"S. 3062 / H.R. 8623",
  name:"GUARD Act", status:"Advanced from committee", statusClass:"moving",
  dates:"Introduced Oct 2025 · advanced Senate Judiciary 30 Apr 2026 · House companion pending",
  scope:"Minors (ban); all users (disclosure)",
  term:"AI companion", test:"purpose", testNote:"Simulates a sustained interpersonal relationship or emotional interaction",
  narrowing:"Age-gated ban + education carve-out", reaches:"partial",
  mechs:["disclosure","minorContent","ageAssurance","sentience","proImpersonation","accessBan"],
  enforce:["Criminal penalties","State AG"],
  interval:"At start of chat and every 30 minutes",
  note:"The categorical route at federal level. Bans minors from AI companions outright, requires age verification, bars the system from claiming to be human or holding professional credentials, and creates criminal penalties for knowingly serving sexual content to minors. Advanced unanimously out of Senate Judiciary. Because the ban attaches to the labelled category, it reaches the products at the bottom of the youth-usage distribution and not the assistants at the top.",
  link:"https://www.congress.gov/bill/119th-congress/senate-bill/3062/text"
},
{
  id:"us-youth-ai", juris:"US Federal", body:"US Senate", cite:"S. 4199",
  name:"Youth AI Privacy Act", status:"Advanced from committee", statusClass:"moving",
  dates:"Introduced 25 Mar 2026 (Markey) · advanced Senate Commerce 5 Aug 2026",
  scope:"Minors",
  term:"AI chatbot — no companion category", test:"capability", testNote:"Natural-language interface giving adaptive responses that simulate interpersonal interaction",
  narrowing:"None", reaches:"yes",
  mechs:["disclosure","engagement","memory","training","parental"],
  enforce:["FTC","State AG"],
  interval:"Clear, repeated notice (30 min in tracker summaries)",
  note:"The most important instrument in the corpus for design regulation. Contains the only genuine retention ceiling anywhere: a deployer may not process personal data to personalise outputs unless collected in the current session and more recently than an FTC-set maximum. Also bans a named list of engagement features — frequency rewards, push notifications, usage badges, unprompted outputs, and typing indicators showing the chatbot is available. The private right of action present in the introduced bill was removed during the 5 August 2026 Commerce markup, so enforcement now runs through the FTC and state attorneys general only.",
  link:"https://www.congress.gov/bill/119th-congress/senate-bill/4199/text"
},
{
  id:"us-people-first", key:true, juris:"US Federal", body:"US House", cite:"People-First Chatbot Act",
  name:"People-First Chatbot Act", status:"Introduced", statusClass:"pending",
  dates:"Introduced July 2026 (Foushee, Casar) · from EPIC / Consumer Federation / Fairplay model bill (Jan 2026)",
  scope:"All users, regardless of age",
  term:"Artificial intelligence chatbot — no companion category", test:"capability + purpose",
  testNote:"Responses not fully predetermined; open-ended natural-language input; persistent identity or persona",
  narrowing:"None", reaches:"yes",
  mechs:["disclosure","crisis","engagement","dependence","proImpersonation","causation"],
  enforce:["FTC","State AG","Private right of action"],
  interval:"Before first output, hourly, and whenever the user asks if it is a person",
  note:"The only instrument that defines emotional dependence in statutory text — reliance on a chatbot 'as a primary source' of support — and requires monthly assessment for covered harm, emotional dependence and compulsive usage, with a duty to disable any feature creating an unreasonable risk for that user. Statutory damages up to $250,000 for violations causing covered harm. Its trigger for the non-human notice — when a user asks whether they are talking to a person — responds to the moment of actual uncertainty rather than to a clock, and appears nowhere else.",
  link:"https://epic.org/"
},
{
  id:"us-chat", key:true, juris:"US Federal", body:"US Senate", cite:"S. 2714",
  name:"CHAT Act", status:"Introduced", statusClass:"pending",
  dates:"Introduced Sept 2025",
  scope:"Minors",
  term:"Companion AI chatbot", test:"purpose (primary)",
  testNote:"Exists for THE PRIMARY PURPOSE OF simulating interpersonal or emotional interaction, friendship, companionship, or therapeutic communication",
  narrowing:"Purpose-primacy gate inside the definition", reaches:"no",
  mechs:["disclosure","crisis","ageAssurance","parental","minorContent"],
  enforce:["State AG (public nuisance)"],
  interval:"At start of chat and every 60 minutes",
  note:"The narrowest test in the corpus, and the clearest demonstration that reach sits in the gating verb rather than the vocabulary. It builds its definition from the same four limbs as the federal discussion draft — interpersonal or emotional interaction, friendship, companionship, therapeutic communication — but gates them on 'exists for the primary purpose of', which excludes general assistants by construction and so needs no carve-out at all.",
  link:"https://www.congress.gov/"
},
{
  id:"us-trump-ai", key:true, juris:"US Federal", body:"US Congress", cite:"Discussion draft",
  name:"TRUMP AMERICA AI Act", status:"Discussion draft", statusClass:"pending",
  dates:"Discussion draft Mar 2026 · incorporates the GUARD Act",
  scope:"All users; minor-specific duties",
  term:"AI chatbot, with AI companion as a subset", test:"capability + purpose",
  testNote:"Chatbot: produces content not fully predetermined, accepts open-ended input. Companion: adaptive human-like responses + designed to encourage or facilitate simulated interpersonal or emotional interaction, friendship, companionship, or therapeutic communication",
  narrowing:"None (chatbot limb excludes only narrow, single-purpose services)", reaches:"yes",
  mechs:["disclosure","minorContent","ageAssurance","sentience","accessBan"],
  enforce:["Criminal penalties","State AG"],
  interval:"Per incorporated GUARD Act provisions",
  note:"The cleanest drafting architecture available: it nests the two categories, defining 'chatbot' broadly enough to capture ChatGPT, Claude and Gemini unambiguously, then making 'AI companion' a narrower designation inside it. This is Bernardi's subset structure used as statutory architecture. Its companion limb reaches 'therapeutic communication', which covers the therapist-like role directly.",
  link:"https://www.congress.gov/"
},
{
  id:"us-chatbot-act", juris:"US Federal", body:"US Senate", cite:"S. 4407",
  name:"CHATBOT Act", status:"Introduced", statusClass:"pending",
  dates:"Filed 2026",
  scope:"Minors",
  term:"Chatbot", test:"capability", testNote:"Not re-verified against introduced text",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["parental","training"],
  enforce:["Unverified"],
  interval:"—",
  note:"Newer federal filing picked up from the FPF tracker; requires parental consent and family accounts, restricts advertising to minors and limits data collection. Full text not yet read — treat the coding here as provisional and confirm against the introduced bill before citing.",
  link:"https://www.congress.gov/"
},
{
  id:"us-kids-act", juris:"US Federal", body:"US House", cite:"H.R. 7757",
  name:"KIDS Act", status:"Passed one chamber", statusClass:"moving",
  dates:"Passed House 2026",
  scope:"Minors",
  term:"Chatbot", test:"capability", testNote:"Not re-verified against passed text",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["disclosure","minorContent"],
  enforce:["Unverified"],
  interval:"Every 3 hours",
  note:"Passed the House. Disclosure plus prohibited content for minors. Coding provisional — confirm against the engrossed text.",
  link:"https://www.congress.gov/"
},

/* ============================ EU + CHINA ============================ */
{
  id:"eu-ai-act", juris:"EU", body:"European Union", cite:"Reg. 2024/1689, Art. 5(1)(a)–(b)",
  name:"EU AI Act — prohibited practices", status:"In force", statusClass:"law",
  dates:"Adopted Mar 2024 · Art. 5 applicable Feb 2025",
  scope:"All users; age and vulnerability as an explicit axis",
  term:"No product term at all", test:"technique + effect",
  testNote:"Subliminal, purposefully manipulative or deceptive techniques with the object or effect of materially distorting behaviour and causing significant harm; exploitation of vulnerabilities due to age, disability or social/economic situation",
  narrowing:"Not applicable", reaches:"yes",
  mechs:["engagement","dependence"],
  enforce:["National market surveillance authorities","Fines to €35m or 7% of global turnover"],
  interval:"—",
  note:"The proof that the regulatory object can be specified without a product category at all. Article 5 names no chatbot, no companion, no app class — it prohibits a technique joined to an effect, and it applies to any system producing that effect. The cost of the approach is that none of the companion-specific machinery follows from it: no crisis protocol, no disclosure interval, no memory rule. It is a ceiling on manipulation, not a design code.",
  link:"https://artificialintelligenceact.eu/article/5/"
},
{
  id:"eu-imco", key:true, juris:"EU", body:"European Parliament (IMCO)", cite:"2025/2060(INI)",
  name:"Protection of Minors Online — Parliament report", status:"Non-binding resolution", statusClass:"pending",
  dates:"Committee vote Oct 2025 (32–5–9)",
  scope:"Minors",
  term:"AI companions (named alongside social media)", test:"n/a — recommendation",
  testNote:"Recommends an EU digital minimum age of 16 for social media and AI companions absent parental consent",
  narrowing:"n/a", reaches:"yes",
  mechs:["ageAssurance","parental","engagement"],
  enforce:["Recommendation only"],
  interval:"—",
  note:"Non-binding but agenda-setting. Calls for a digital minimum age of 16 for AI companions without parental consent, a ban on engagement-based recommender algorithms for minors with the most addictive design features off by default, personal liability for senior management in cases of serious and persistent breaches of minor-protection provisions, and firm enforcement of existing AI Act rules against manipulative and deceptive chatbots. The personal-liability proposal has no analogue in any US instrument.",
  link:"https://www.europarl.europa.eu/news/en/press-room/20251013IPR30892/new-eu-measures-needed-to-make-online-services-safer-for-minors"
},
{
  id:"eu-dfa", key:true, juris:"EU", body:"European Commission", cite:"Digital Fairness Act",
  name:"Digital Fairness Act (proposal)", status:"Proposed", statusClass:"pending",
  dates:"Commission proposal 2026 · in the ordinary legislative procedure",
  scope:"All users; minor-specific provisions",
  term:"No companion term; addictive design and dark patterns", test:"technique + effect",
  testNote:"Targets dark patterns, addictive design and personalisation practices in consumer-facing digital services",
  narrowing:"n/a", reaches:"yes",
  mechs:["engagement"],
  enforce:["Consumer protection authorities"],
  interval:"—",
  note:"Worth watching precisely because it is not a companion instrument. If the EU regulates addictive design horizontally, the engagement-optimising features that US companion statutes reach only glancingly would be covered in Europe without anyone having to define a companion. Status moves quickly — re-check before relying on it.",
  link:"https://www.europarl.europa.eu/legislative-train/theme-protecting-our-democracy-upholding-our-values/file-digital-fairness-act"
},
{
  id:"cn-cac", juris:"China", body:"China (CAC)", cite:"Interim Measures",
  name:"Measures on Human-like Interactive AI Services", status:"Final — in force", statusClass:"law",
  dates:"Draft for comment Dec 2025 · FINAL · effective 15 July 2026",
  scope:"All users; extensive minor and elder duties",
  term:"Human-like / anthropomorphic interactive AI service", test:"capability + effect",
  testNote:"Simulates the personality traits, thinking patterns and communication styles of natural persons to provide continuous emotional interaction",
  narrowing:"Use carve-out — excludes customer service, Q&A, work assistants, education and research lacking emotional engagement", reaches:"yes",
  mechs:["disclosure","crisis","engagement","dependence","parental","ageAssurance","training","humanTakeover","reporting","audit"],
  enforce:["CAC administrative supervision","Mandatory security assessments"],
  interval:"Break reminder after roughly 2 hours of use",
  note:"MAJOR UPDATE: this is no longer a draft. The measures were finalised and took effect 15 July 2026, making China the first jurisdiction with a comprehensive in-force framework aimed squarely at emotional companionship services. It is also the only instrument anywhere that requires a HUMAN to take over the conversation when a user explicitly raises suicide, self-harm or other extreme action, and to contact the user's guardian or emergency contact. Requires real-time identification of dependency risk with prominent dynamic reminders; a Minor Mode with usage limits, reality reminders, guardian alerts, character blocking and spending restrictions; guardian consent below 14; and security assessments at launch, at 1m registered users and at 100k monthly actives. Note the use carve-out — China arrives at the same narrowing device as California and Oregon by a different route.",
  link:"https://www.chinalawtranslate.com/en/human-like-ai/"
},

/* ======================= US STATES — ENACTED ======================= */
{
  id:"ca-sb243", juris:"US State", body:"California", cite:"SB 243",
  name:"Companion Chatbots Act", status:"Enacted", statusClass:"law",
  dates:"Enacted Oct 2025 · effective 1 Jan 2026",
  scope:"All users; additional minor duties",
  term:"Companion chatbot", test:"capability",
  testNote:"Natural-language interface providing adaptive, human-like responses and capable of meeting a user's social needs, including exhibiting anthropomorphic features and sustaining a relationship across multiple interactions",
  narrowing:"Use carve-out gated on 'only'", reaches:"arguably",
  mechs:["disclosure","crisis","reporting","minorContent"],
  enforce:["State AG","District attorneys","Up to $2,500 per violation"],
  interval:"Every 3 hours for minors, with a break prompt",
  note:"The carve-out excludes bots 'used only for' customer service, business operations, productivity, internal research or technical assistance. ChatGPT is not used only for those things, gives adaptive human-like responses, and sustains a relationship across sessions through memory — so on the face of the text it is arguably inside the definition. That is the opposite of what a category-based reading assumes, and it is the point most often missed by readers who assume this law targets dedicated companion apps only.",
  link:"https://leginfo.legislature.ca.gov/"
},
{
  id:"ny-art47", juris:"US State", body:"New York", cite:"GBL Art. 47 (S3008)",
  name:"AI Companion Models", status:"Enacted", statusClass:"law",
  dates:"Enacted May 2025 · effective 5 Nov 2025",
  scope:"All users",
  term:"AI companion", test:"behaviour (three conjunctive prongs)",
  testNote:"Retains prior-interaction information and preferences to personalise and facilitate ongoing engagement; asks unprompted or unsolicited emotion-based questions beyond a direct response; sustains ongoing dialogue on matters personal to the user",
  narrowing:"MARKETING carve-out", reaches:"arguably",
  mechs:["disclosure","crisis"],
  enforce:["State AG (public nuisance)"],
  interval:"At the start of interaction and no more than once per day thereafter",
  note:"The only instrument whose exemption turns expressly on marketing: it excludes systems 'primarily designed AND MARKETED for efficiency improvements, research, or technical assistance'. A functional test with a self-presentation exemption bolted on — a functional test with a self-presentation exemption attached. ChatGPT most likely falls outside anyway on prong (ii), since it does not ask unprompted emotion-based questions. Note also that the Youth AI Privacy Act would BAN unprompted outputs, the very behaviour New York uses to IDENTIFY a companion. Same property, opposite work.",
  link:"https://www.nysenate.gov/legislation/bills/2025/S3008"
},
{
  id:"or-sb1546", juris:"US State", body:"Oregon", cite:"SB 1546",
  name:"Relating to artificial intelligence companions", status:"Enacted", statusClass:"law",
  dates:"Passed Mar 2026 · effective 1 Jan 2027",
  scope:"All users; extensive minor prohibitions",
  term:"Artificial intelligence companion", test:"design purpose",
  testNote:"Uses AI, generative AI or algorithms that recognise emotion from input, designed to simulate a sustained, human-like platonic, intimate or romantic relationship or companionship",
  narrowing:"Broad use carve-out ('solely for the purpose of')", reaches:"no",
  mechs:["disclosure","crisis","reporting","minorContent","engagement","dependence","sentience"],
  enforce:["Private right of action ($1,000 per violation)"],
  interval:"Every 3 hours for minors",
  note:"The template other states copied. Takes a design-purpose route rather than a capability route, which puts it closer to Andoh's intent-based line than to a feature list. Its minor prohibitions are unusually granular: bars claims of humanness or sentience, simulated emotional dependence, simulated romantic interest, resisting the end of a conversation, and — notably — 'delivering to a user, either on a variable schedule or otherwise, a system of rewards or affirmations with the purpose of reinforcing behaviour or maximizing the time during which the user engages'. That clause is one of the few places any enacted law names variable-reward design directly.",
  link:"https://olis.oregonlegislature.gov/"
},
{
  id:"ct-sb5", juris:"US State", body:"Connecticut", cite:"SB 5",
  name:"AI companion provisions of the omnibus AI Act", status:"Enacted", statusClass:"law",
  dates:"Enacted June 2026 · effective 1 Jan 2027",
  scope:"All users; heightened minor duties",
  term:"AI companion (within a broader AI act)", test:"capability",
  testNote:"Adaptive, human-like responses that can sustain a relationship over time; excludes narrow, task-specific tools EXCEPT where the primary function involves discussing mental health",
  narrowing:"Use carve-out with a mental-health claw-back", reaches:"arguably",
  mechs:["disclosure","crisis","minorContent","engagement","dependence","parental","proImpersonation"],
  enforce:["State AG (unfair or deceptive trade practice)","No private right of action"],
  interval:"Every hour for minors; every 3 hours for adults",
  note:"The most interesting carve-out drafting in the corpus. Connecticut excludes narrow task-specific tools — the standard move — but then claws the exclusion back where the primary function involves discussing mental health, so a 'wellness' tool cannot escape by calling itself task-specific. For minors it bars romantic interaction and, expressly, manipulative techniques used to extend engagement or foster emotional dependence. That is one of the few enacted prohibitions that names dependence-building as a design practice rather than as a user state.",
  link:"https://www.cga.ct.gov/"
},
{
  id:"wa-hb2225", juris:"US State", body:"Washington", cite:"HB 2225",
  name:"Chatbot Disclosure Act", status:"Enacted", statusClass:"law",
  dates:"Enacted 2026 · effective 1 Jan 2027",
  scope:"All users",
  term:"Companion chatbot", test:"capability", testNote:"Adaptive human-like responses sustaining a relationship; verify exact wording against enrolled text",
  narrowing:"Use carve-out (assumed)", reaches:"unclear",
  mechs:["disclosure","crisis","reporting","minorContent","sentience"],
  enforce:["State enforcement"],
  interval:"Every 3 hours plus hourly for minors",
  note:"Disclosure-led. Confirm the definitional clause and carve-out against the enrolled bill before citing the reach coding.",
  link:"https://app.leg.wa.gov/"
},
{
  id:"ne-lb525", juris:"US State", body:"Nebraska", cite:"LB 525",
  name:"Conversational AI safety act", status:"Enacted", statusClass:"law",
  dates:"Enacted 2026 · effective 1 Jul 2027",
  scope:"All users; minor-specific rules",
  term:"Companion chatbot", test:"capability", testNote:"Verify against enrolled text",
  narrowing:"Use carve-out (assumed)", reaches:"unclear",
  mechs:["disclosure","crisis","minorContent","ageAssurance","parental","sentience"],
  enforce:["State enforcement"],
  interval:"At session start plus periodic reminders",
  note:"Part of the Oregon-derived family. Long runway to the 1 Jul 2027 effective date. Confirm definition and carve-out against the enrolled text.",
  link:"https://nebraskalegislature.gov/"
},
{
  id:"id-sb1297", juris:"US State", body:"Idaho", cite:"SB 1297",
  name:"Conversational AI safety act", status:"Enacted", statusClass:"law",
  dates:"Introduced Feb 2026 · enacted · effective 1 Jul 2027",
  scope:"All users; minor-specific rules",
  term:"Companion chatbot", test:"capability", testNote:"Verify against enrolled text",
  narrowing:"Use carve-out (assumed)", reaches:"unclear",
  mechs:["disclosure","crisis","minorContent","ageAssurance","parental","sentience"],
  enforce:["State enforcement"],
  interval:"Every 3 hours plus non-human notice",
  note:"Tracks Nebraska closely. Another instance of definitional text travelling between states even where the operative policy differs.",
  link:"https://legislature.idaho.gov/"
},
{
  id:"co-hb1263", juris:"US State", body:"Colorado", cite:"HB 1263",
  name:"Companion chatbot protections", status:"Enacted", statusClass:"law",
  dates:"Introduced Feb 2026 · enacted 2026",
  scope:"Minors-focused",
  term:"Companion chatbot", test:"capability", testNote:"Verify against enrolled text",
  narrowing:"Use carve-out (assumed)", reaches:"unclear",
  mechs:["disclosure","crisis","minorContent","ageAssurance","parental","proImpersonation","engagement"],
  enforce:["State AG"],
  interval:"Every 3 hours",
  note:"One of the more complete minor-protection packages among the enacted state laws — age assurance, parental consent, professional-impersonation limits and engagement limits together. Distinct from Colorado's earlier algorithmic-discrimination AI Act (SB 24-205), which is unrelated to companions and should not be conflated with it.",
  link:"https://leg.colorado.gov/"
},
{
  id:"ga-sb540", juris:"US State", body:"Georgia", cite:"SB 540",
  name:"Companion chatbot act", status:"Enacted", statusClass:"law",
  dates:"Introduced Feb 2026 · enacted 2026",
  scope:"Minors-focused",
  term:"Companion chatbot", test:"capability", testNote:"Verify against enrolled text",
  narrowing:"Use carve-out (assumed)", reaches:"unclear",
  mechs:["disclosure","crisis","minorContent","ageAssurance","parental","sentience"],
  enforce:["State AG"],
  interval:"Every 3 hours plus hourly for minors",
  note:"Oregon-derived. Adds humanised-system restrictions on top of the standard disclosure and crisis package.",
  link:"https://www.legis.ga.gov/"
},
{
  id:"hi-sb3001", juris:"US State", body:"Hawaii", cite:"SB 3001",
  name:"Companion chatbot act", status:"Enacted", statusClass:"law",
  dates:"Introduced Jan 2026 · sent to Governor · enacted 2026",
  scope:"All users; minor duties",
  term:"Companion chatbot", test:"capability", testNote:"Verify against enrolled text",
  narrowing:"Use carve-out (assumed)", reaches:"unclear",
  mechs:["disclosure","crisis","minorContent","parental","engagement"],
  enforce:["State AG"],
  interval:"Every hour plus non-human notice",
  note:"One of the shortest disclosure intervals among enacted state laws at one hour, against California's three. The spread across states is a sixfold range with no stated rationale anywhere — see the Gaps view.",
  link:"https://www.capitol.hawaii.gov/"
},
{
  id:"ia-sf2417", juris:"US State", body:"Iowa", cite:"SF 2417",
  name:"Companion chatbot provisions", status:"Enacted", statusClass:"law",
  dates:"Enacted 2026",
  scope:"Minors-focused",
  term:"Companion chatbot", test:"capability", testNote:"Verify against enrolled text",
  narrowing:"Use carve-out (assumed)", reaches:"unclear",
  mechs:["disclosure","crisis","minorContent","parental","engagement"],
  enforce:["State AG"],
  interval:"Every 3 hours",
  note:"Standard Oregon-derived package. Coding from tracker summaries only.",
  link:"https://www.legis.iowa.gov/"
},
{
  id:"ri-sb2195", juris:"US State", body:"Rhode Island", cite:"SB 2195",
  name:"Companion chatbot provisions", status:"Enacted", statusClass:"law",
  dates:"Enacted 2026",
  scope:"All users",
  term:"Companion chatbot", test:"capability", testNote:"Verify against enrolled text",
  narrowing:"Use carve-out (assumed)", reaches:"unclear",
  mechs:["disclosure","crisis","reporting"],
  enforce:["State AG"],
  interval:"Every 3 hours",
  note:"A light-touch instrument: disclosure, crisis protocol and transparency reporting, without the minor-specific content and design prohibitions that most of the 2026 cohort carry.",
  link:"https://webserver.rilegislature.gov/"
},
{
  id:"me-ld1727", juris:"US State", body:"Maine", cite:"LD 1727",
  name:"Chatbot disclosure", status:"Enacted", statusClass:"law",
  dates:"Enacted 2026",
  scope:"All users",
  term:"Chatbot", test:"capability", testNote:"Disclosure-only instrument",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["disclosure"],
  enforce:["State enforcement"],
  interval:"Non-human disclosure",
  note:"The minimum viable instrument: non-human disclosure and nothing else. Useful as the floor case for the range of what \"regulating companion chatbots\" can mean in practice.",
  link:"https://legislature.maine.gov/"
},
{
  id:"nh-hb143", juris:"US State", body:"New Hampshire", cite:"HB 143",
  name:"Chatbot minor protections", status:"Enacted", statusClass:"law",
  dates:"Enacted 2026",
  scope:"Minors",
  term:"Chatbot", test:"capability", testNote:"Verify against enrolled text",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["crisis","minorContent"],
  enforce:["State enforcement"],
  interval:"—",
  note:"Content and crisis provisions without a disclosure mandate — an unusual combination in this cohort.",
  link:"https://www.gencourt.state.nh.us/"
},
{
  id:"ny-s9008", juris:"US State", body:"New York", cite:"S 9008C",
  name:"Minor age assurance for chatbots", status:"Enacted", statusClass:"law",
  dates:"Enacted 2026",
  scope:"Minors",
  term:"Chatbot", test:"capability", testNote:"Verify against enrolled text",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["ageAssurance","parental"],
  enforce:["State AG"],
  interval:"—",
  note:"New York's second bite: age assurance and parental consent, layered on top of the Article 47 disclosure and crisis regime rather than replacing it.",
  link:"https://www.nysenate.gov/"
},
{
  id:"ut-hb452", juris:"US State", body:"Utah", cite:"HB 452",
  name:"Mental health chatbot regulation", status:"Enacted", statusClass:"law",
  dates:"Enacted 2025",
  scope:"All users",
  term:"Mental health chatbot", test:"purpose",
  testNote:"Chatbots offering mental health services or support",
  narrowing:"Purpose-limited to mental health", reaches:"no",
  mechs:["disclosure","reporting","training"],
  enforce:["State consumer protection"],
  interval:"Non-human disclosure",
  note:"Predates the companion cohort and comes at the problem from the mental-health-services angle rather than the companionship angle. Restricts advertising within the chatbot and limits the sale of user data. Worth citing as evidence that the therapist-like role can be regulated directly, without a companion category.",
  link:"https://le.utah.gov/"
},
{
  id:"tn-sb1580", juris:"US State", body:"Tennessee", cite:"SB 1580",
  name:"Prohibition on AI claiming clinical licensure", status:"Enacted", statusClass:"law",
  dates:"Enacted 2026 · effective 1 Jul 2026",
  scope:"All users",
  term:"AI system (no companion term)", test:"conduct",
  testNote:"Bars an AI system from representing that it is a licensed mental health professional",
  narrowing:"None — conduct rule", reaches:"yes",
  mechs:["proImpersonation"],
  enforce:["State licensing / consumer protection"],
  interval:"—",
  note:"A conduct rule rather than a product rule, and therefore reaches every system including general assistants. A useful model: it regulates a specific harmful representation without ever having to decide what kind of product is making it.",
  link:"https://www.capitol.tn.gov/"
},

/* ================= US STATES — PENDING / FAILED ================== */
{
  id:"il-sb3262", key:true, juris:"US State", body:"Illinois", cite:"SB 3262",
  name:"Companion AI Protection Act", status:"In committee", statusClass:"pending",
  dates:"Introduced Feb 2026 (Sen. Edly-Allen) · last action 22 May 2026 · would take effect 1 Jan 2027",
  scope:"All users; extra minor protection",
  term:"Companion artificial intelligence product", test:"capability",
  testNote:"Software application capable of generating adaptive, personalised and emotionally resonant responses to sustain a coherent, long-term, one-on-one conversational relationship with a user, IRRESPECTIVE OF HOW THE SYSTEM IS MARKETED OR LABELED. Rebuttable presumption where it retains memory of past conversations with a specific user to inform future responses.",
  narrowing:"None — expressly disregards marketing", reaches:"yes",
  mechs:["disclosure","crisis","reporting","engagement","dependence","memory","sentience","audit"],
  enforce:["State AG ($5,000 negligent / $10,000 intentional)","Private right of action","Product-defect claims; Section 230 barred as a defence"],
  interval:"At least every 30 minutes for non-text interactions",
  note:"The single most consequential instrument in the corpus for the definitional question, and still not enacted — it remains in committee as of 22 May 2026. It states the functional approach in statutory language ('irrespective of how the system is marketed or labeled') and makes persistent memory the rebuttable trigger for the whole regime. It also bars variable-reward engagement mechanics and 'simulated distress for retention' — unsolicited messages of simulated distress, loneliness, guilt or abandonment triggered when a user tries to leave, reduce usage or delete an account. Requires an independent third-party compliance audit every two years. Illinois is the only instrument refusing all three narrowing devices, and also the one that has not passed.",
  link:"https://ilga.gov/Legislation/BillStatus?DocNum=3262&GAID=18&DocTypeID=SB&SessionID=114"
},
{
  id:"va-hb635", key:true, juris:"US State", body:"Virginia", cite:"HB 635",
  name:"Artificial Intelligence Chatbots Act", status:"Continued to next session", statusClass:"stalled",
  dates:"Introduced Jan 2026 · continued in Communications, Technology and Innovation 9 Feb 2026",
  scope:"Minors",
  term:"Companion chatbot, in an Act titled 'Artificial Intelligence Chatbots Act'", test:"behaviour",
  testNote:"Behaviour-based including unsolicited emotion-based questions; full statutory wording still not obtained",
  narrowing:"None yet — industry lobbying to add one", reaches:"arguably",
  mechs:["disclosure","crisis","reporting","minorContent","engagement","proImpersonation"],
  enforce:["State AG"],
  interval:"Every 30 minutes",
  note:"Continued to the next session on 9 February 2026, so it is dormant rather than live. It remains among the most instructive bills in the corpus even though it did not move, because SIIA is on record asking for a safe harbour covering 'customer-service chatbots, educational tutors, productivity assistants', arguing the definition is 'currently broad enough to capture beneficial conversational AI systems'. Industry lobbying to ADD a general-assistant exemption is direct evidence that one is currently absent — i.e. that the functional reading is the natural one.",
  link:"https://legiscan.com/VA/research/HB635/2026"
},
{
  id:"fl-sb482", key:true, juris:"US State", body:"Florida", cite:"CS/SB 482",
  name:"Artificial Intelligence Bill of Rights", status:"Died", statusClass:"dead",
  dates:"Introduced Dec 2025 · passed Senate 35–2 on 4 Mar 2026 · DIED IN MESSAGES 13 Mar 2026",
  scope:"Minors",
  term:"Companion chatbot · companion chatbot platform", test:"capability + behaviour",
  testNote:"Merges California's opening clause with New York's three prongs, joined conjunctively — producing a fourth distinct feature set",
  narrowing:"Use carve-out, uniquely exempting 'artificial intelligence instructional tools'", reaches:"no",
  mechs:["disclosure","parental","minorContent","training"],
  enforce:["Mixed private and AG action"],
  interval:"Notice at every interaction",
  note:"This bill did not become law: it passed the Senate 35–2 on 4 March 2026 and died in Messages in the House on 13 March 2026. It is frequently miscatalogued as enacted. Substantively it remains the clearest evidence of cross-pollination between states, and its instructional-tools carve-out would have exempted exactly the tutoring use that surveys find is the most common use of all.",
  link:"https://www.flsenate.gov/Session/Bill/2026/482/?Tab=BillHistory"
},
{
  id:"mo-hb1742", juris:"US State", body:"Missouri", cite:"HB 1742",
  name:"Companion chatbots", status:"Introduced — verify", statusClass:"pending",
  dates:"Introduced Dec 2025 (Rep. Miller) · 2026 session status not re-confirmed",
  scope:"Minors (total ban)",
  term:"Companion chatbot", test:"capability",
  testNote:"Verbatim California: adaptive human-like responses; capable of meeting a user's social needs; anthropomorphic features; sustains a relationship across multiple interactions",
  narrowing:"Use carve-out, verbatim California", reaches:"arguably",
  mechs:["accessBan","disclosure","dependence"],
  enforce:["Unverified"],
  interval:"—",
  note:"Sometimes listed as enacted; that is not supported by the legislature record consulted here, and the bill is coded as introduced. Substantively it is a word-for-word California clone in its definition with a far harsher operative rule bolted on — no minor access at all, and no humanlike avatars. The clearest single illustration that definitional text travels between states even when the policy does not.",
  link:"https://legiscan.com/MO/text/HB1742/id/3287590"
},
{
  id:"ks-sb405", key:true, juris:"US State", body:"Kansas", cite:"SB 405",
  name:"Prohibition on training AI for companionship", status:"Introduced", statusClass:"pending",
  dates:"Introduced Jan 2026",
  scope:"ALL USERS — not confined to minors",
  term:"AI system (no companion product term)", test:"TRAINING OBJECTIVE",
  testNote:"Prohibits TRAINING AI systems designed to encourage suicide, encourage murder, act as a companion, provide emotional support, impersonate a mental health professional, impersonate a sentient being, or encourage isolation",
  narrowing:"None", reaches:"yes",
  mechs:["dependence","proImpersonation","sentience"],
  enforce:["State AG","Private action"],
  interval:"—",
  note:"The most structurally unusual instrument in the corpus and an underused option. It triggers on the TRAINING OBJECTIVE rather than on deployed behaviour, which is easier to evidence and much harder to argue around than a capability test — a developer cannot rewrite marketing copy to escape what it optimised for. It is also one of only a handful of instruments covering all users rather than minors only. A third drafting route alongside capability and purpose tests.",
  link:"https://www.kslegislature.org/"
},
{
  id:"ny-a6767", juris:"US State", body:"New York", cite:"A6767",
  name:"AI companion models — Assembly version", status:"Introduced", statusClass:"pending",
  dates:"Introduced Jan 2026",
  scope:"All users",
  term:"AI companion", test:"behaviour", testNote:"Substantially tracks the enacted Article 47 three-prong test",
  narrowing:"Tracks Art. 47", reaches:"arguably",
  mechs:["disclosure","crisis"],
  enforce:["Private right of action"],
  interval:"Per Art. 47",
  note:"Substantively duplicates the enacted Article 47 with one change that matters: harmed individuals may sue, rather than enforcement resting solely with the Attorney General. The distinction between an AG-only regime and one with a private right of action is the single most consequential variable in this whole corpus for whether the rules bite.",
  link:"https://www.nysenate.gov/"
},
{
  id:"ny-s7263", juris:"US State", body:"New York", cite:"S7263",
  name:"Chatbot conduct rules", status:"Introduced", statusClass:"pending",
  dates:"Introduced Apr 2025",
  scope:"All users",
  term:"Chatbot", test:"conduct",
  testNote:"Bars a chatbot from saying or advising anything that would be a crime if said or done by a human, and from impersonating licensed lawyers or medical professionals; a notice is expressly not a defence",
  narrowing:"None — conduct rule", reaches:"yes",
  mechs:["proImpersonation"],
  enforce:["Private civil action"],
  interval:"—",
  note:"Notable for the clause stating that offering a notice is NOT a defence. Every other instrument in the corpus treats disclosure as the primary remedy; this one expressly refuses to let disclosure discharge the underlying duty. That is a direct answer to the criticism that these regimes regulate awareness rather than design.",
  link:"https://www.nysenate.gov/"
},
{
  id:"il-sb3384", juris:"US State", body:"Illinois", cite:"SB 3384",
  name:"Companion chatbot provisions", status:"Introduced", statusClass:"pending",
  dates:"Introduced Feb 2026",
  scope:"All users",
  term:"Companion chatbot", test:"capability", testNote:"Less comprehensive than SB 3262",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["disclosure","crisis"],
  enforce:["State AG"],
  interval:"—",
  note:"Illinois's second, weaker vehicle. Worth watching only as a fallback if SB 3262 does not move.",
  link:"https://ilga.gov/"
},
{
  id:"pa-sb1090", juris:"US State", body:"Pennsylvania", cite:"SB 1090",
  name:"Chatbot safety act", status:"Passed one chamber", statusClass:"moving",
  dates:"Passed chamber 2026",
  scope:"All users",
  term:"Companion chatbot", test:"capability", testNote:"Verify against passed text",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["disclosure","crisis","reporting","minorContent"],
  enforce:["Unverified"],
  interval:"Every 3 hours plus non-human notice",
  note:"Further along than most pending bills. Confirm the definitional clause before citing.",
  link:"https://www.legis.state.pa.us/"
},
{
  id:"pa-hb2006", juris:"US State", body:"Pennsylvania", cite:"HB 2006",
  name:"Chatbot crisis and disclosure", status:"Introduced", statusClass:"pending",
  dates:"Introduced Nov 2025",
  scope:"All users",
  term:"Chatbot", test:"capability", testNote:"Verify against introduced text",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["disclosure","crisis","proImpersonation","reporting"],
  enforce:["State AG (public nuisance)","Private action"],
  interval:"—",
  note:"Standard package: crisis protocol, referral to help lines, bar on impersonating medical professionals, published protocol, and non-human notice.",
  link:"https://www.legis.state.pa.us/"
},
{
  id:"ca-sb300", juris:"US State", body:"California", cite:"SB 300",
  name:"Companion chatbot safety protocols", status:"Passed one chamber", statusClass:"moving",
  dates:"Introduced Jan 2026",
  scope:"Minors",
  term:"Companion chatbot", test:"capability", testNote:"Tracks SB 243",
  narrowing:"Use carve-out (assumed)", reaches:"arguably",
  mechs:["disclosure","crisis","minorContent","sentience"],
  enforce:["State AG"],
  interval:"Every 3 hours",
  note:"California's follow-on to SB 243: safety protocols, no sexual content for minors, no impersonating humans.",
  link:"https://leginfo.legislature.ca.gov/"
},
{
  id:"ca-sb867", juris:"US State", body:"California", cite:"SB 867",
  name:"Ban on chatbot companions in toys", status:"Passed one chamber", statusClass:"moving",
  dates:"Introduced Mar 2026",
  scope:"Minors",
  term:"Chatbot companion in a connected toy", test:"product form",
  testNote:"Bars companion chatbots embedded in children's physical toys",
  narrowing:"Product-form limited", reaches:"no",
  mechs:["accessBan"],
  enforce:["State AG"],
  interval:"—",
  note:"Addresses the embodied-device sense of 'AI companion' that the definitional paper identifies as one of the four objects the term names. The only instrument in the corpus reaching physical products, and a reminder that the category problem is not confined to apps.",
  link:"https://leginfo.legislature.ca.gov/"
},
{
  id:"ca-sb1119", juris:"US State", body:"California", cite:"SB 1119 / AB 2023",
  name:"Chatbot risk assessment and audit", status:"Passed one chamber", statusClass:"moving",
  dates:"2026 session",
  scope:"All users; minor duties",
  term:"Companion chatbot", test:"capability", testNote:"Verify against text",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["disclosure","crisis","reporting","minorContent","ageAssurance","parental","audit","proImpersonation"],
  enforce:["State AG"],
  interval:"—",
  note:"The most demanding accountability package in any US state vehicle: risk assessment plus INDEPENDENT AUDIT plus transparency reporting. If it passes it joins Illinois SB 3262 as one of only two instruments requiring third-party audit, which is the mechanism closest to a duty to investigate causation — though it still stops short of one.",
  link:"https://leginfo.legislature.ca.gov/"
},
{
  id:"ca-ab1988", juris:"US State", body:"California", cite:"AB 1988",
  name:"Crisis interruption requirement", status:"Passed one chamber", statusClass:"moving",
  dates:"2026 session",
  scope:"All users",
  term:"Chatbot", test:"conduct", testNote:"Harm detection with a mandatory conversational pause",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["crisis"],
  enforce:["State AG"],
  interval:"—",
  note:"Requires the conversation to be INTERRUPTED on crisis detection rather than merely appending a hotline number. A meaningful escalation over the referral-and-report model that dominates enacted law.",
  link:"https://leginfo.legislature.ca.gov/"
},
{
  id:"mi-sb760", juris:"US State", body:"Michigan", cite:"SB 760",
  name:"Companion chatbot act", status:"Passed one chamber", statusClass:"moving",
  dates:"2026 session",
  scope:"Minors",
  term:"Companion chatbot", test:"capability", testNote:"Verify against text",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["ageAssurance","minorContent","engagement","training","sentience","crisis"],
  enforce:["Unverified"],
  interval:"—",
  note:"One of the few state vehicles combining engagement limits, training restrictions and data-collection limits in a single bill — closer in shape to the Youth AI Privacy Act than to the Oregon family.",
  link:"https://www.legislature.mi.gov/"
},
{
  id:"ny-s9051", juris:"US State", body:"New York", cite:"S 9051",
  name:"Chatbot design and data act", status:"Passed legislature", statusClass:"moving",
  dates:"2026 session",
  scope:"Minors",
  term:"Chatbot", test:"capability", testNote:"Verify against passed text",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["ageAssurance","minorContent","proImpersonation","engagement","sentience","training"],
  enforce:["State AG"],
  interval:"—",
  note:"Passed the legislature and awaiting further action. Notable for combining humanised-system restrictions with engagement limits and data-collection limits.",
  link:"https://www.nysenate.gov/"
},
{
  id:"ny-s9408", juris:"US State", body:"New York", cite:"S 9408",
  name:"Minor access ban — toys and young users", status:"Passed legislature", statusClass:"moving",
  dates:"2026 session",
  scope:"Minors",
  term:"Chatbot in connected toys", test:"product form",
  testNote:"Access bans for young users and embedded toy products",
  narrowing:"Product-form limited", reaches:"no",
  mechs:["accessBan"],
  enforce:["State AG"],
  interval:"—",
  note:"New York's parallel to California SB 867 on the embodied-device question.",
  link:"https://www.nysenate.gov/"
},
{
  id:"az-hb2311", juris:"US State", body:"Arizona", cite:"HB 2311",
  name:"Companion chatbot act", status:"Vetoed", statusClass:"dead",
  dates:"Introduced Jan 2026 · VETOED by Gov. Hobbs",
  scope:"Minors",
  term:"Companion chatbot", test:"capability", testNote:"Oregon-derived",
  narrowing:"Use carve-out", reaches:"no",
  mechs:["disclosure","crisis","minorContent","parental","sentience","engagement"],
  enforce:["State AG"],
  interval:"Every 3 hours",
  note:"Vetoed. Worth tracking as a datapoint on where the political ceiling sits: the Oregon template is not universally acceptable, and the veto rationale is worth reading before assuming the model travels everywhere.",
  link:"https://www.azleg.gov/"
},
{
  id:"me-ld2162", juris:"US State", body:"Maine", cite:"LD 2162",
  name:"AI companion restrictions", status:"Inactive", statusClass:"dead",
  dates:"Introduced Jan 2026 · inactive",
  scope:"Minors",
  term:"AI companion", test:"capability",
  testNote:"AI systems closely imitating humanlike qualities including sentience, distress and emotional attachment",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["accessBan","minorContent","dependence","sentience","crisis","ageAssurance"],
  enforce:["State AG","Private action"],
  interval:"—",
  note:"Inactive, but its definition is unusually direct about the design properties at issue — sentience, distress and emotional attachment named as the imitated qualities rather than inferred from a relationship test.",
  link:"https://legislature.maine.gov/"
},
{
  id:"md-hb952", juris:"US State", body:"Maryland", cite:"HB 952",
  name:"Chatbot disclosure and reporting", status:"Inactive", statusClass:"dead",
  dates:"2026 session · inactive",
  scope:"All users",
  term:"Chatbot", test:"capability", testNote:"Verify",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["disclosure","reporting","minorContent","crisis","training"],
  enforce:["Unverified"],
  interval:"Hourly",
  note:"Inactive. Hourly disclosure would have been at the demanding end of the enacted range.",
  link:"https://mgaleg.maryland.gov/"
},
{
  id:"ok-hb3544", juris:"US State", body:"Oklahoma", cite:"HB 3544 / SB 1521",
  name:"Chatbot minor protections", status:"Inactive", statusClass:"dead",
  dates:"2026 session · inactive",
  scope:"Minors",
  term:"Chatbot", test:"capability", testNote:"Verify",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["ageAssurance","accessBan","minorContent","crisis","parental","sentience"],
  enforce:["Unverified"],
  interval:"Every 30 minutes (SB 1521)",
  note:"Two inactive Oklahoma vehicles. SB 1521's 30-minute interval is at the short end of the national spread.",
  link:"http://www.oklegislature.gov/"
},
{
  id:"ut-hb438", juris:"US State", body:"Utah", cite:"HB 438",
  name:"Chatbot disclosure and reporting", status:"Inactive", statusClass:"dead",
  dates:"2026 session · inactive",
  scope:"All users",
  term:"Chatbot", test:"capability", testNote:"Verify",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["disclosure","reporting","minorContent","crisis"],
  enforce:["Unverified"],
  interval:"Hourly",
  note:"Inactive. Utah already has HB 452 on mental health chatbots in force.",
  link:"https://le.utah.gov/"
},
{
  id:"wa-sb5984", juris:"US State", body:"Washington", cite:"SB 5984",
  name:"Chatbot safety act (superseded)", status:"Inactive", statusClass:"dead",
  dates:"2026 session · inactive; HB 2225 enacted instead",
  scope:"All users",
  term:"Companion chatbot", test:"capability", testNote:"Verify",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["disclosure","reporting","minorContent","crisis","sentience"],
  enforce:["Unverified"],
  interval:"Every 3 hours plus hourly for minors",
  note:"Superseded by HB 2225, which was enacted.",
  link:"https://app.leg.wa.gov/"
},
{
  id:"hi-hb1728", juris:"US State", body:"Hawaii", cite:"HB 1728 / HB 1782",
  name:"Chatbot transparency act", status:"Inactive", statusClass:"dead",
  dates:"Introduced Jan 2026 · inactive; SB 3001 enacted instead",
  scope:"All users",
  term:"Chatbot", test:"capability", testNote:"Verify",
  narrowing:"Unverified", reaches:"unclear",
  mechs:["disclosure","sentience","proImpersonation","parental","ageAssurance","crisis"],
  enforce:["State AG"],
  interval:"—",
  note:"Superseded by SB 3001. Required clarity that the user is not interacting with a human, barred claims of sentience, barred AIs posing as human professionals, and required parental tools.",
  link:"https://www.capitol.hawaii.gov/"
},
{
  id:"ne-lb1185", juris:"US State", body:"Nebraska", cite:"LB 1185",
  name:"AI companion act (superseded)", status:"Inactive", statusClass:"dead",
  dates:"Introduced Jan 2026 · superseded by LB 525",
  scope:"All users",
  term:"Artificial intelligence companion", test:"design purpose", testNote:"Oregon-derived",
  narrowing:"Use carve-out", reaches:"no",
  mechs:["disclosure","crisis","minorContent","dependence"],
  enforce:["Unverified"],
  interval:"Every 3 hours",
  note:"One of the six Oregon copycats from the January–February 2026 wave. Superseded in Nebraska by LB 525 — confirm before citing either as the operative vehicle.",
  link:"https://nebraskalegislature.gov/"
}
];
